# Generated by Django 5.1.1 on 2024-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='flag_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
